services:
#    app_main.example:
#        class: App\Bundle\MainBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    redirect.after.login:
        class:  App\Bundle\MainBundle\EventHandler\AfterLoginRedirection
        arguments: ['@router']

    redirect.after.logout:
        class:  App\Bundle\MainBundle\EventHandler\AfterLogoutRedirection
        arguments: ['@router']

    jolydays_dev4_manager:
        abstract: true
        arguments:
                - '@doctrine.orm.default_entity_manager'
                - '@request_stack'
                - '@kernel'

    jolydays_dev4_annonce_manager:
        class: App\Bundle\MainBundle\Manager\AnnoncesManager
        parent: jolydays_dev4_manager

    jolydays_dev4_upload_file:
        class: App\Bundle\MainBundle\Services\FileUploader
        arguments: ['%upload_directory%']